#:schema node_modules/wrangler/config-schema.json
name = "london-gaelic-choir"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js"
assets = { directory = "./dist", binding = "ASSETS" }

[observability]
enabled = true
