#:schema node_modules/wrangler/config-schema.json
name = "london-gaelic-choir"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"
assets = { directory = "./dist", binding = "ASSETS" }

routes = [{pattern = "coisirlunnainn.dev", custom_domain = true}]

[observability]
enabled = true

[[send_email]]
name = "SEND"
destination_address = "samuelpmacleod@icloud.com"